language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 7.1
  - 7.2
  - hhvm
matrix:
  allow_failures:
  - php: hhvm

install:
  - composer self-update
  - composer install --prefer-dist --dev
  - composer info --installed
script: phpunit -c phpunit.xml